# Generated by Django 3.1.3 on 2020-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.TextField(default='기타', null=True),
        ),
    ]
