# Generated by Django 3.1.3 on 2020-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ALT',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='LAT',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
